# Generated by Django 5.0.1 on 2024-01-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
