# Generated by Django 5.0.1 on 2024-01-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0002_remove_post_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
