# Generated by Django 4.2.9 on 2024-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0003_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
